FROM node:6.10.0-alpine
LABEL name="React Forecast-Me Dev Container"
LABEL version="1.0"

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Copy Config Files
COPY ./.eslintrc.json /app
COPY ./.eslintignore /app
COPY ./.flowconfig /app

# Copy dependencies and install
COPY ./package.json /app
RUN npm install

RUN mkdir /app/client
COPY ./client/ /app/client

EXPOSE 3005
CMD ["npm", "start"]