FROM node:8.8.1-alpine
LABEL name="React Forecast-Me Dev Container"
LABEL version="1.0"

ENV NPM_CONFIG_LOGLEVEL info
# Create app directory
RUN mkdir -p /src
WORKDIR /src

# Copy dependencies and install
COPY ./client/ ./
RUN npm install

EXPOSE 3000
CMD ["npm", "start"]