FROM node:8.8.1-alpine
LABEL name="Forecast Me API Container"
LABEL version="1.0"

# Setup working directory for the server container
RUN mkdir /server
WORKDIR /server

# Copy server files over and install dependencies
COPY ./server/ ./
RUN npm install

EXPOSE 3006
EXPOSE 5858
CMD ["npm", "run", "start:server:dev"]