version: "3"

services:
  forecast-me-react:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-client-dev
    env_file:
      - ./local.env
    volumes:
      - ../client/:/app/client/
    ports:
      - "3000:3000"
    links:
      - forecast-me-server
  forecast-me-server:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-server-dev
    env_file:
      - ./local.env
    volumes:
      - ../server/:/src/server/
    ports:
      - "3001:3001"
      - "5050:5050"