version: "3"

services:
  forecast-me-react:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-client-dev
    env_file:
      - ./local.env
    volumes:
      - ../client/src:/src/src/
      - ../client/config:/src/config/
      - ../client/public:/src/public/
    ports:
      - "3005:3005"
    links:
      - forecast-me-server
  redis:
    image: redis:4.0.2-alpine
  forecast-me-server:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-server-dev
    env_file:
      - ./local.env
    volumes:
      - ../server/bin:/server/bin/
      - ../server/controllers:/server/controllers/
      - ../server/models:/server/models/
      - ../server/helpers:/server/helpers/
      - ../server/routes:/server/routes/
      - ../server/services:/server/services/
    ports:
      - "3006:3006"
      - "5050:5050"