version: "3"

services:
  react:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-client-dev
    env_file:
      - ./local.env
    volumes:
      - ../client/src:/src/src/
      - ../client/src/components:/src/src/components/
      - ../client/config:/src/config/
      - ../client/public:/src/public/
    ports:
      - "3005:3005"
    links:
      - server
    depends_on:
      - server
  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"
  server:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-server-dev
    env_file:
      - ./local.env
    volumes:
      - ../server/bin:/server/bin/
      - ../server/controllers:/server/controllers/
      - ../server/models:/server/models/
      - ../server/helpers:/server/helpers/
      - ../server/routes:/server/routes/
      - ../server/services:/server/services/
      - ../server/redis:/server/redis/
    ports:
      - "5858:5858"
      - "3006:3006"
    links:
      - redis
    depends_on:
      - redis