version: "2"

services:
  forecast-me:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-prod
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"