version: "3"

services:
  forecast-me:
    build:
      context: ../
      dockerfile: docker-compose/dockerfiles/Dockerfile-prod
    environment:
      - NODE_ENV=production
      - BABEL_ENV=production
    ports:
      - "3006:3006"
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"